### ISSUE TITLE
Null pointer on MultipartUtil.turnIntoMultipart

### ISSUE THREAD

**Issue by Stuff-Stuffs** [AlexIIL/LibMultiPart#10]
Using simple-pipes as an example I have created a block as well as a block entity. The block entity on tick calls MultipartUtil.turnIntoMultipart(world, pos), this is based on TileTank in simple-pipes.
This was the result https://gist.github.com/Stuff-Stuffs/facbc361ac1da515472f321d3e7acbbf

**Comment by AlexIIL** [comment]
Thanks - looks like I broke the logic a little while ago, although it shouldn't be too difficult to fix.

I've pushed 0.3.4-pre.1 to the [maven](https://mod-buildcraft.com/maven/alexiil/mc/lib/libmultipart-all/0.3.4-pre.1/), but 0.3.4 will probably have more than just this fix.
