### ISSUE TITLE
Multiparts loaded from structure blocks don't send their data to the client

### ISSUE THREAD

**Issue by LemmaEOF** [AlexIIL/LibMultiPart#12]
When loaded from a structure NBT file (from a structure block or from [Nomad Books](https://github.com/Ladysnake/Nomad-Books)), multipart blocks forget what blocks they contain and become unbreakable with no hitbox.

**Comment by AlexIIL** [comment]
From a quick test, this doesn't seem to be quite the case: multiparts *do* save and load correctly, however the server BE doesn't send it's information to the client.

(So there's obviously still an issue, but it's not quite as bad as the title suggests).

**Comment by LemmaEOF** [comment]
oh, that's a much more fixable problem, good.

**Comment by AlexIIL** [comment]
This seems to be fixed in 0.4.0. (Although it might have been fixed in an earlier release, but I didn't test).
