### ISSUE TITLE
Mod compatibility Issue: Baritone

### ISSUE THREAD

**Issue by Mhowser** [AlexIIL/LibMultiPart#13]
I'm using a Pathfinding mod called Baritone, and when I was building a multipart, the game crashed. Now I am unable to join the world, unless I remove Baritone.

[Crash log](https://gist.githubusercontent.com/Cloak-Bot/023d02c30fdc4a8f955c6d99e5826b7d/raw/22644dd40a5829bbbdb8315ff3d7ab8e35f43e5a/crash.txt)

Fabritone (baritone for fabric) https://gitlab.com/CDAGaming/fabritone

**Comment by AlexIIL** [comment]
None of the parameters for `BlockState.getCollisionShape()` are marked as nullable, so I think this is a fabritone bug - they should be passing `EmptyBlockView.INSTANCE` instead.

(In other words, can you report this to them instead).

**Comment by Mhowser** [comment]
Alright, I can forward the issue to the baritone devs, thanks for the info.
