### ISSUE TITLE
Multipart containers cull faces regardless of adjacent block transparency

### ISSUE THREAD

**Issue by ghost** [AlexIIL/LibMultiPart#14]
It appears that multipart containers cull faces regardless of whether or not the block adjacent to them is transparent or not. This is most apparent if you place glass next to a multipart container as in the example below.

![Multipart Cullface Issue](https://user-images.githubusercontent.com/18454093/72764035-8ed12280-3ba3-11ea-8126-fa436d11e6cb.png)

**Comment by ghost** [comment]
Also seen with a torch on a fence post because for whatever reason it appears fences are automatically multipart containers even when they don't need to be. 
![Torch On Fence](https://user-images.githubusercontent.com/18454093/72764231-6f86c500-3ba4-11ea-8c09-453e8092a839.png)

**Comment by AlexIIL** [comment]
They don't for me:
![image](https://user-images.githubusercontent.com/3751138/72764659-125d3480-3be1-11ea-9b57-55b903c841d0.png)

What version of minecraft, LMP, and other mods are you using?

**Comment by ghost** [comment]
I limited down the mods, the issue occurs with LibMultipart (0.3.3) and just Vanilla Parts (beta 1.1.2 for 1.15.1). In hindsight it's probably an issue with Vanilla Parts, I'll go report the issue over there.

Side question, which mod is the one you're using to test, with the vertical slabs and vanilla multiparts? I wasn't aware of any other implementation of vanilla multiparts.

**Comment by AlexIIL** [comment]
SimplePipes has facades (copied from buildcraft) which I expanded to include slab-like, half-slabs, quarter-slabs, and some corner variants.

(I use simple pipes as a test mod to ensure that everything works in my libs)
