### ISSUE TITLE
Allow the ignorance of entities in turnIntoMultipart

### ISSUE THREAD

**Issue by 0blu** [AlexIIL/LibMultiPart#15]
Hey,

when a block is placed and an entity is colliding with the new multipart that is created with `turnIntoMultipart`, the function returns `null` and the block was not converted.

I don't see any benefits of this behavior since the block that is converted should already cleared the space around it. 
https://github.com/AlexIIL/LibMultiPart/blob/6f5bb67a700d2c639213f5e623e836f963f59e81/src/main/java/alexiil/mc/lib/multipart/impl/MultipartUtilImpl.java#L71

**Comment by AlexIIL** [comment]
That would make sense

**Comment by 0blu** [comment]
Thanks 😃
