### ISSUE TITLE
Fences do not allow leashing mobs

### ISSUE THREAD

**Issue by Naofal-Helal** [AlexIIL/LibMultiPart#19]
LibMultiPart version: 0.3.6

when this mod overrides fences from *any other mod including vanilla*, **leashes do not attach at all**.

**Comment by AlexIIL** [comment]
LibMultiPart doesn't modify vanilla behaviour, or add any multiparts. This is a bug with VanillaParts (https://github.com/Juuxel/VanillaParts/issues/11)
