### ISSUE TITLE
Parts always play stone sounds when the player mines them

### ISSUE THREAD

**Issue by Juuxel** [AlexIIL/LibMultiPart#20]
This probably needs a new method in `AbstractPart`. :wink:

**Comment by AlexIIL** [comment]
Ok, this should finally be implemented and usable in 0.4.7 via [AbstractPart.playHitSound(PlayerEntity)](https://alexiil.uk/javadoc/libmultipart/0.4.7/alexiil/mc/lib/multipart/api/AbstractPart.html#playHitSound(net.minecraft.entity.player.PlayerEntity)) and [AbstractPart.playBreakSound()](https://alexiil.uk/javadoc/libmultipart/0.4.7/alexiil/mc/lib/multipart/api/AbstractPart.html#playBreakSound()). *(Although you may want to override [AbstractPart.getClosestBlockState()](https://alexiil.uk/javadoc/libmultipart/0.4.7/alexiil/mc/lib/multipart/api/AbstractPart.html#getClosestBlockState()) instead)*.
