### ISSUE TITLE
Port for 1.17

### ISSUE THREAD

**Issue by lucsoft** [AlexIIL/LibMultiPart#23]
I would love to see this lib to be working with fabric's 1.17 version

**Comment by AlexIIL** [comment]
I don't really have time to follow 1.17 snapshots, so I won't be porting any of my libs to 1.17 myself. However I'm happy to merge PRs to [0.4.x-mc1.17.x](https://github.com/AlexIIL/LibMultiPart/tree/0.4.x-mc1.17.x) and push releases to my maven if you'd like to try porting it? (Or anyone else who wants this to be ported)

**Comment by AlexIIL** [comment]
...and now that 1.17 has reached release candidates I should have LBA, LNS, LMP, and simple pipes ported to 1.17 in the next few hours.

**Comment by AlexIIL** [comment]
Released!

LMP is at `0.6.0`.

**Comment by lucsoft** [comment]
@AlexIIL great work :)
