### ISSUE TITLE
Singleplayer server (java.lang.IllegalStateException: [LibMultiPart] We've gotten out of sync! )

### ISSUE THREAD

**Issue by Cheeseborgers** [AlexIIL/LibMultiPart#29]
Was Playing a single player world, came back though the nether to my base. and started to dig in spawn area chunks. To get a "Saving World" dialog, stating "java.lang.IllegalStateException: [LibMultiPart] We've gotten out of sync! (Expected to be in the middle of drawing block outlines when we're not!)".

I've attached a gist link to the crash-report  [https://gist.github.com/Cheeseborgers/c6ab28971194407da046360df15aa0f4](hhttps://gist.github.com/Cheeseborgers/c6ab28971194407da046360df15aa0f4)

**Comment by AlexIIL** [comment]
I think this should start working if you manually update LibMultiPart to [0.5.0](https://alexiil.uk/maven/alexiil/mc/lib/libmultipart-all/0.5.0/libmultipart-all-0.5.0.jar)?

**Comment by Cheeseborgers** [comment]
Haven't recreated it in a survival world/copy since the update.
