### ISSUE TITLE
Missing translation for block.libmultipart.container

### ISSUE THREAD

**Issue by Qendolin** [AlexIIL/LibMultiPart#46]
The block libmultipart:container does not have a translation in the lang file, so much such as [WTHIT](https://modrinth.com/mod/wthit) don't know what to call it and show "block.libmultipart.container".

**Comment by AlexIIL** [comment]
...I committed this back here: https://github.com/AlexIIL/LibMultiPart/commit/a0485b88a5993bb699c4bac36777aace73542dc0 and forgot to comment on this issue sorry - but this should be fixed in 0.7.2?

**Comment by Qendolin** [comment]
You didn't put the json file in the 'lang' directory. It works after I created the directory and moved the file manually.

**Comment by AlexIIL** [comment]
oh. Thanks for pointing that out, I've moved it into a `lang` folder in [0.7.3-pre.3](https://alexiil.uk/maven/alexiil/mc/lib/libmultipart-all/0.7.3-pre.3/libmultipart-all-0.7.3-pre.3.jar).

**Comment by Kneelawk** [comment]
Using WTHIT with LMP now, this issue appears to be fixed.

**Comment by Kneelawk** [comment]
I am going to mark this issue as completed, as this seems to be working correctly since `0.7.3-pre.3`.
