### ISSUE TITLE
Add a static convenience method PartDefinition.add(PartDefinition) 

### ISSUE THREAD

**Issue by natanfudge** [AlexIIL/LibMultiPart#6]
That will add to the PartDefinition.PARTS map
Since a `PartDefinition` already has an `Identifier`, there's no point specifying  (at the API consumption) the same `Identifier` as the key.

**Comment by AlexIIL** [comment]
It already exists - just call `register(Identifier...)` without any arguments, as the passed array is only for migrating old names.

However the documentation could be improved (added) for this, and I could add a second (no-arg) `register()` method for clarity?

**Comment by AlexIIL** [comment]
I added this for 0.2.1, sorry for not responding before then...
