### ISSUE TITLE
1.15 support

### ISSUE THREAD

**Issue by natanfudge** [AlexIIL/LibMultiPart#7]
Currently it breaks because of a LibNetworkStack mixin error.

**Comment by AlexIIL** [comment]
I haven't updated any of my libs to 1.15 quite yet - although you might want to try compiling https://github.com/Fuyukai/LibNetworkStack for now instead?

(As 1.15-pre has come out though I'm started to port everything properly if you're ok waiting a few days)

**Comment by natanfudge** [comment]
That's fine. Ping me when you're done please :)

**Comment by AlexIIL** [comment]
Ok! I'll close this issue when I release it - will that be good enough?

**Comment by natanfudge** [comment]
Yes that will do

**Comment by AlexIIL** [comment]
Released - 0.6.1.
