### ISSUE TITLE
MultipartUtil.get() overload with IWorld

### ISSUE THREAD

**Issue by Juuxel** [AlexIIL/LibMultiPart#8]
`IWorld` offers enough methods for getting the multipart container, and it would be useful in a context where there's only `IWorld` (that can be a `ChunkRegion` instead of a `World`).

**Comment by AlexIIL** [comment]
Ok, I've pushed a version (0.2.1) to the BC maven which allows `BlockView`'s as well.

**Comment by AlexIIL** [comment]
Erm, I should probably have closed this a while ago...
