### ISSUE TITLE
A critical error occurrednet.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: libmultipart requires {libblockattributes_core @ [>=0.6.3]}

### ISSUE THREAD

**Issue by gamingoninsulin** [AlexIIL/LibMultiPart#9]
MultiMC version: 0.6.7-1375MultiMC version: 0.6.7-1375

Minecraft folder is:C:/Users/User/Downloads/multimc/MultiMC/instances/modded 1.15/.minecraft

Java path is:C:/Program Files (x86)/Common Files/Oracle/Java/javapath/javaw.exe

Java is versie 1.8.0_231 met 64-bit architectuur.

Main Class:  net.fabricmc.loader.launch.knot.KnotClient
Native path:  C:/Users/User/Downloads/multimc/MultiMC/instances/modded 1.15/natives
Traits:traits FirstThreadOnMacOS
Libraries:  C:/Users/User/Downloads/multimc/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/com/mojang/patchy/1.1/patchy-1.1.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/net/fabricmc/intermediary/1.15/intermediary-1.15.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/net/fabricmc/tiny-mappings-parser/0.2.0.11/tiny-mappings-parser-0.2.0.11.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/net/fabricmc/sponge-mixin/0.8+build.17/sponge-mixin-0.8+build.17.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/net/fabricmc/tiny-remapper/0.2.0.52/tiny-remapper-0.2.0.52.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/com/google/jimfs/jimfs/1.1/jimfs-1.1.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/org/ow2/asm/asm/7.2/asm-7.2.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/org/ow2/asm/asm-analysis/7.2/asm-analysis-7.2.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/org/ow2/asm/asm-commons/7.2/asm-commons-7.2.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/org/ow2/asm/asm-tree/7.2/asm-tree-7.2.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/org/ow2/asm/asm-util/7.2/asm-util-7.2.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/net/fabricmc/fabric-loader/0.7.3+build.176/fabric-loader-0.7.3+build.176.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/com/mojang/minecraft/1.15/minecraft-1.15-client.jar
Native libraries:  C:/Users/User/Downloads/multimc/MultiMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar  C:/Users/User/Downloads/multimc/MultiMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar
Mods:  [✔️] Adorn-1.6.3+1.15.1  [✔️] advancements-enlarger-1.0.0  [✔️] Allure-1.1.5  [✔️] AppleSkin-mc1.12-1.0.9  [✔️] aquarius-1.4.0+1.15  [✔️] autoswitch-0.10.0  [✔️] bamboo-block-justfatlard-0.1.0  [✔️] bamboo-spikes-justfatlard-0.1.0  [✔️] beebetter-1.6.0  [✔️] beeproductive-1.0.1+1.15.1  [✔️] bettersleeping-0.3.0  [✔️] BetterThanMending-1.1.2  [✔️] better-wither-skeletons-1.0.0  [✔️] blockus-1.3.0  [✔️] buffer-1.14.4-1.8.4  [✔️] bunch-o-trinkets-1.0.0  [✔️] chickenfeathers-1.2.1  [✔️] cloth-events-1.1.0  [✔️] Couplings-1.3.1  [✔️] customtitlescreen-1.15-0.0.5  [✔️] demeter-1.1.3  [✔️] diggusmaximus-1.2.5  [✔️] ding-3.0.0  [✔️] dirttopath-1.3.1  [❌] DurabilityViewer-1.12-forge14.21.1.2387-1.6.jar (disabled)  [✔️] expandedstorage-4.9.35+1.15.1  [❌] Experience-Container-1.4.jar (disabled)  [✔️] extradoors-1.3.0-1.15  [✔️] extrapieces-2.8.3  [✔️] extra-pressure-plates-1.1.3  [✔️] fabriblocks-1.1.6  [✔️] fabric-api-0.4.27+build.286-1.15  [✔️] fabric-diagonal-panes-0.1.5  [✔️] fabric-furnaces_1.15pre4-1.2.0  [✔️] fabric-language-groovy-1.0.2.local  [✔️] farmcraft-v1.0.1-build-3-19w41a  [✔️] FatExperienceOrbs-0.0.6  [✔️] fiber2cloth-1.2.1  [✔️] Flax-1.1.1  [❌] glassdoor-1.4.3.jar (disabled)  [❌] hard-hat-steve-1.1.0.jar (disabled)  [❌] HealthOverlay-1.15-2.2.10.jar (disabled)  [✔️] Hwyla-1.8.26-B41_1.12.2  [❌] immersive-portals-1.15-5.jar (disabled)  [❌] improved-stations-1.2.1.jar (disabled)  [❌] informedload-4.0.0.jar (disabled)  [❌] InventorySorter-1.6.3.jar (disabled)  [❌] ironbarrels-2.1.0.jar (disabled)  [❌] jumpoverfences-1.15-0.0.1.jar (disabled)  [❌] leaf-decay-1.1.1.jar (disabled)  [✔️] libblockattributes-all-0.6.3  [❌] lumen-Beta+0.4.1.jar (disabled)  [✔️] Mambience-1.0.0+1.14  [✔️] Materialisation-2.2.1  [✔️] mod_Autofish_0.7.3_mc1.12.1  [✔️] mod_voxelMap_1.7.1_for_1.12.2  [✔️] modmenu-1.8.2+build.18  [✔️] ModNameToolTips-1.1.1  [✔️] MoEnchantments-1.8.5-1.14.4  [✔️] Mo-Glass-v1.1-MC1.15  [✔️] monkeys-mod-1.0.0  [✔️] moreberries-1.2.3  [✔️] mousewheelie-1.3.10+1.15.1-pre1  [✔️] nice-to-have-1.2.2  [✔️] notenoughcrashes-1.2.0+1.15.1  [✔️] oldobsidian-fabric-1.0.0  [✔️] optifabric-0.7.1  [✔️] potionofbees-1.15.1-1.0.0  [✔️] PresenceFootsteps-r21+1.15  [✔️] raa-2.0.0+build.431  [✔️] realisticclouds-1.15-0.0.1  [✔️] RebornCore-1.12.2-3.16.4.478-universal  [✔️] requiem-1.1.2  [✔️] Retro-Exchange-1.12.2-1.0.7  [✔️] rgbblocks-2.1.1  [✔️] right-click-clear-1.1.1-unstable.201912010707  [✔️] RoughlyEnoughItems-3.3.1  [✔️] simplepipes-all-0.3.3  [✔️] simple-utilities-mod-1.0.0  [✔️] simplexterrain-0.4.3  [✔️] smokeextender-1.3.0  [✔️] SmoothScrollingEverywhere-2.2.1-unstable.201912010747  [✔️] snowdrift-1.0.1  [✔️] StatsKeeper-1.15-1.1.4  [✔️] tdnf-mc115-1.8.69  [✔️] TechReborn-1.12.2-2.24.3.1043-universal  [✔️] tinycoals-0.0.5  [✔️] tinyconfig-1.1.2  [✔️] trumpet-skeleton-fabric-1.1.1  [✔️] VanillaParts-1.1.1+1.14.4  [✔️] villager-hats-fabric-1.15.0-1.0.0  [✔️] WildWorld-1.2.0+1.15  [✔️] yet-another-gravestone-mod-1.2.1
Params:  --username  --version MultiMC5 --gameDir C:/Users/User/Downloads/multimc/MultiMC/instances/modded 1.15/.minecraft --assetsDir C:/Users/User/Downloads/multimc/MultiMC/assets --assetIndex 1.15 --uuid  --accessToken  --userType  --versionType release
Window size: 854 x 480
Java Arguments:[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms384m, -Xmx3635m, -Duser.language=en]

Minecraft process ID: 8152

Using onesix launcher.
[19:34:57] [main/INFO]: Loading for game Minecraft 1.15[19:35:01] [main/FATAL]: A critical error occurrednet.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: libmultipart requires {libblockattributes_core @ [>=0.6.3]} at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:170) ~[fabric-loader-0.7.3+build.176.jar:?] at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:603) ~[fabric-loader-0.7.3+build.176.jar:?] at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:176) ~[fabric-loader-0.7.3+build.176.jar:?] at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:166) [fabric-loader-0.7.3+build.176.jar:?] at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127) [fabric-loader-0.7.3+build.176.jar:?] at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.7.3+build.176.jar:?] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_231] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_231] at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_231] at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?] at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?] at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ? at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-loader-sat4j-2.3.5.4.jar:?] at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-loader-sat4j-2.3.5.4.jar:?] at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-loader-sat4j-2.3.5.4.jar:?] at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-loader-sat4j-2.3.5.4.jar:?] at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:168) ~[fabric-loader-0.7.3+build.176.jar:?] ... 13 moreProcess exited with code 1.Clipboard copy at: 03 Jan 2020 19:35:19 +0100

**Comment by AlexIIL** [comment]
...Ah. Woops - I didn't know that https://gist.github.com required you to have a user account - I'll start recommending pastebin instead.

However now that you do have a github account could you move the log to a [new gist](https://gist.github.com)?

**Comment by AlexIIL** [comment]
Erm, could you try extracting `libblockattributes-core-0.6.3.jar` out of `libblockattributes-all-0.6.3.jar` to see if that makes a difference?

**Comment by gamingoninsulin** [comment]
@AlexIIL  how do i do that do i need a program for it? or someting

**Comment by AlexIIL** [comment]
You should be able to rename it from `.jar` to `.zip` and then open it with windows explorer?

**Comment by gamingoninsulin** [comment]
hey that worked thanks a lot
